export const FETCH_APARTMENTS_LIST = 'FETCH_APARTMENTS_LIST';
export const FETCH_APARTMENT = 'FETCH_APARTMENT';
export const FETCH_APARTMENTS_START = 'FETCH_APARTMENTS_START';
export const UPDATE_APPLIED_FILTER = 'UPDATE_APPLIED_FILTER';